{"name": "test_case_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 2) == 12", "trace": "def test_case_3():\n>       assert 1 +2 ==12\nE       assert (1 + 2) == 12\n\ntest_demo1.py:8: AssertionError"}, "attachments": [{"name": "log", "source": "9edcd3ef-0916-4932-bacb-14db8a3e938e-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d196b83f-c545-47b4-ac4b-ba71122f866e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1953469b-f830-41a8-80b1-090e7edc1e2b-attachment.txt", "type": "text/plain"}], "start": 1549196964847, "stop": 1549196964849, "uuid": "09333846-e17a-4e92-a3e2-6ca6bf5bc8fe", "historyId": "8f5e8b768a3709849cb588f4f6e37dd0", "fullName": "test_demo1#test_case_3", "labels": [{"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "Xiaobos-MacBook-Air.local"}, {"name": "thread", "value": "2752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo1"}]}